# -*- coding: utf-8 -*-
"""Triplet_loss_for_Recognition_Pytorch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XZk2eituiqkxv1COlrEknmH5mYKMs0e
"""

import os
import numpy as np
import torch
import torchvision.datasets as dset
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset, TensorDataset
from torch.optim import *
import torchvision
import matplotlib.pyplot as plt
from dataset import SiameseNetworkDataset
from config import Config
from net_archi import SiameseNetwork
from torch import optim

# Triplet Loss
class TripletLoss(nn.Module):
    def __init__(self, margin):
        super(TripletLoss, self).__init__()
        self.margin = margin
    def forward(self, anchor, positive, negative, size_average = True):
        distance_positive = (anchor - positive).pow(2).sum(1)
        distance_negative = (anchor - negative).pow(2).sum(1)
        losses = F.relu(distance_positive - distance_negative + self.margin)
        return losses.mean() if size_average else losses.sum()

folder_dataset = dset.ImageFolder(root=Config.training_dir)
siamese_dataset = SiameseNetworkDataset(imageFolderDataset=folder_dataset,
                                        transform=transforms.Compose([transforms.Resize((512,512)),
                                                                      transforms.ToTensor()
                                                                      ])
                                       ,should_invert=False)
train_dataloader = DataLoader(siamese_dataset,
                        shuffle=True,
                        num_workers=8,
                        batch_size=Config.train_batch_size)

net = SiameseNetwork().cuda()
criterion = TripletLoss(margin = 0.2)
optimizer = optim.Adam(net.parameters(),lr = 0.0005 )

counter = []
loss_history = [] 
iteration_number= 0

checkpoint = {'model': SiameseNetwork(),
          'state_dict': net.state_dict(),
          'optimizer' : optimizer.state_dict()}

for epoch in range(0,Config.train_number_epochs):
    for i, data in enumerate(train_dataloader,0):
        img0, img1 , label = data
        img0, img1 , label = img0.cuda(), img1.cuda() , label.cuda()
        optimizer.zero_grad()
        output1,output2 = net(img0,img1)
        loss_triplet = criterion(output1,output2)
        loss_triplet.backward()
        optimizer.step()
        if i %10 == 0 :
            print("Epoch number {}\n Current loss {}\n".format(epoch,loss_triplet.item()))
            iteration_number +=10
            counter.append(iteration_number)
            loss_history.append(loss_triplet.item())
            torch.save(checkpoint, 'checkpoint.pth')

